"""Regenerate the public demo fixtures in `demo-data/`.

    make demo-fixtures

The fixtures are produced by running the **real scanners and the real pricing
service** against a `moto` sandbox. That matters for three reasons:

1. Field shapes, nulls, and cost values come from production code paths, so the
   demo cannot drift from what the API actually returns. (A test enforces this —
   see `tests/test_demo_fixtures.py`.)
2. Every identifier is generated by moto, so no real account or resource ID can
   leak into a public artifact. Sanitization is structural, not a cleanup step.
3. It costs nothing and needs no AWS credentials, so anyone can reproduce it.

The two synthetic accounts are separate `mock_aws` contexts. The "previous" scan
is *derived* from the current one rather than generated independently, because
resource IDs must be stable across both for the diff to be meaningful.
"""

from __future__ import annotations

import json
import sys
from copy import deepcopy
from datetime import UTC, datetime, timedelta
from pathlib import Path

import boto3
from moto import mock_aws
from moto.moto_api._internal import mock_random

# moto invents resource IDs randomly, which would make every regeneration churn
# the whole fixture set and silently invalidate the committed screenshots.
# Seeding makes `make demo-fixtures` reproducible: same input, same IDs.
RANDOM_SEED = 20260817

REPO_ROOT = Path(__file__).resolve().parents[2]
BACKEND = REPO_ROOT / "backend"
OUT_DIR = REPO_ROOT / "demo-data"

sys.path.insert(0, str(BACKEND))

from app.services import evaluate_alerts, scan_all  # noqa: E402
from app.services.diff_service import diff_resource_lists  # noqa: E402

SANDBOX = {"account_id": "111122223333", "label": "sandbox-lab", "region": "us-east-1"}
TRAINING = {"account_id": "444455556666", "label": "training-account", "region": "us-west-2"}

CURRENT_DT = datetime(2026, 8, 17, 14, 5, 11, 884000, tzinfo=UTC)
PREVIOUS_DT = datetime(2026, 8, 14, 8, 12, 44, 201000, tzinfo=UTC)


def _iso(moment: datetime) -> str:
    return moment.isoformat(timespec="milliseconds").replace("+00:00", "Z")


CURRENT_AT = _iso(CURRENT_DT)
CURRENT_SCAN_ID = f"{CURRENT_AT}_3b9f2ad1"
PREVIOUS_AT = _iso(PREVIOUS_DT)
PREVIOUS_SCAN_ID = f"{PREVIOUS_AT}_7c1e93af"

# How old each demo resource is at the time of the current scan.
#
# The scanners read the real `LaunchTime` / `CreateTime` / `CreationDate`, but
# moto stamps those with the wall clock at generation time: every fixture
# resource would be zero days old, and the values would churn on every run,
# taking the committed screenshots with them. Age is the whole point of the
# field, so the ages are pinned here — matched on a substring of the resource's
# name or id, which the seed keeps stable.
DEMO_AGE_DAYS = {
    "tutorial-web-server": 87,  # the oldest finding — the demo's headline
    "tutorial-scratch-volume": 74,
    "lab-vpc-nat": 39,
    "lab-alb": 68,
    "cloud-lab-artifacts-2026": 212,
    "workshop-node-01": 61,
    "student-sandbox-07": 23,
    "training-postgres": 96,
    "classroom-submissions-archive": 154,
}
# Root volumes, which the scanner reports untagged and unnamed.
DEFAULT_AGE_DAYS = 61


def _network(ec2, region: str, azs: list[str]):
    """A VPC with one subnet per AZ (load balancers need two)."""
    vpc = ec2.create_vpc(CidrBlock="10.0.0.0/16")["Vpc"]["VpcId"]
    subnets = []
    for i, az in enumerate(azs):
        subnets.append(
            ec2.create_subnet(VpcId=vpc, CidrBlock=f"10.0.{i + 1}.0/24", AvailabilityZone=az)[
                "Subnet"
            ]["SubnetId"]
        )
    return vpc, subnets


def _tag(ec2, resource_id: str, name: str) -> None:
    ec2.create_tags(Resources=[resource_id], Tags=[{"Key": "Name", "Value": name}])


def seed_sandbox(region: str) -> None:
    """The classic 'left a tutorial running' account."""
    ec2 = boto3.client("ec2", region_name=region)
    vpc, subnets = _network(ec2, region, [f"{region}a", f"{region}b"])
    ami = "ami-0c55b159cbfafe1f0"

    # Running instance from a half-finished tutorial.
    running = ec2.run_instances(ImageId=ami, MinCount=1, MaxCount=1, InstanceType="t3.micro")[
        "Instances"
    ][0]["InstanceId"]
    _tag(ec2, running, "tutorial-web-server")

    # Stopped instance — cheap, but its volume is not.
    stopped = ec2.run_instances(ImageId=ami, MinCount=1, MaxCount=1, InstanceType="t3.small")[
        "Instances"
    ][0]["InstanceId"]
    _tag(ec2, stopped, "workshop-node-01")
    ec2.stop_instances(InstanceIds=[stopped])

    # Orphaned volume nobody remembers creating.
    orphan = ec2.create_volume(AvailabilityZone=f"{region}a", Size=100, VolumeType="gp3")[
        "VolumeId"
    ]
    _tag(ec2, orphan, "tutorial-scratch-volume")

    # Unassociated Elastic IP — billed hourly, attached to nothing.
    eip = ec2.allocate_address(Domain="vpc")
    _tag(ec2, eip["AllocationId"], "left-over-lab-ip")

    # NAT Gateway: the classic surprise line item. Tag its address too, or the
    # scanner falls back to showing the raw public IP as the resource name.
    nat_eip = ec2.allocate_address(Domain="vpc")
    _tag(ec2, nat_eip["AllocationId"], "lab-vpc-nat-address")
    nat = ec2.create_nat_gateway(SubnetId=subnets[0], AllocationId=nat_eip["AllocationId"])[
        "NatGateway"
    ]["NatGatewayId"]
    _tag(ec2, nat, "lab-vpc-nat")

    # Load balancer with nothing behind it.
    elbv2 = boto3.client("elbv2", region_name=region)
    elbv2.create_load_balancer(
        Name="lab-alb", Subnets=subnets, Scheme="internet-facing", Type="application"
    )

    boto3.client("s3", region_name=region).create_bucket(Bucket="cloud-lab-artifacts-2026")


def seed_training(region: str) -> None:
    """A shared classroom account."""
    ec2 = boto3.client("ec2", region_name=region)
    _network(ec2, region, [f"{region}a", f"{region}b"])
    ami = "ami-0c55b159cbfafe1f0"

    instance = ec2.run_instances(ImageId=ami, MinCount=1, MaxCount=1, InstanceType="t3.medium")[
        "Instances"
    ][0]["InstanceId"]
    _tag(ec2, instance, "student-sandbox-07")

    # Elastic IP that IS in use — still billed since Feb 2024, but low risk.
    eip = ec2.allocate_address(Domain="vpc")
    _tag(ec2, eip["AllocationId"], "bastion-address")
    eni = ec2.create_network_interface(SubnetId=ec2.describe_subnets()["Subnets"][0]["SubnetId"])[
        "NetworkInterface"
    ]["NetworkInterfaceId"]
    ec2.associate_address(AllocationId=eip["AllocationId"], NetworkInterfaceId=eni)

    rds = boto3.client("rds", region_name=region)
    rds.create_db_instance(
        DBInstanceIdentifier="training-postgres",
        DBInstanceClass="db.t3.micro",
        Engine="postgres",
        MasterUsername="admin",
        MasterUserPassword="not-a-real-password",
        AllocatedStorage=20,
    )

    boto3.client("s3", region_name=region).create_bucket(
        Bucket="classroom-submissions-archive",
        CreateBucketConfiguration={"LocationConstraint": region},
    )


# moto stamps every ARN with this account; rewrite it so ARNs agree with the
# synthetic account each resource is attributed to.
MOTO_ACCOUNT_ID = "123456789012"


def pin_age(item: dict) -> None:
    """Replace moto's wall-clock timestamp with a fixed, plausible age.

    Left alone when the scanner reported no creation time at all (Elastic IPs),
    so the fixture keeps showing what a real scan of that service shows.
    """
    if not item.get("created_at"):
        return
    key = item.get("name") or item["resource_id"]
    days = next((d for needle, d in DEMO_AGE_DAYS.items() if needle in key), DEFAULT_AGE_DAYS)
    item["created_at"] = _iso(CURRENT_DT - timedelta(days=days))


def scan_account(seed_fn, account: dict) -> list[dict]:
    """Run the real scanners in an isolated moto account and stamp ownership."""
    with mock_aws():
        mock_random.seed(RANDOM_SEED)
        seed_fn(account["region"])
        result = scan_all(regions=[account["region"]])

    resources = []
    for resource in result["resources"]:
        item = resource.model_dump(mode="json")
        item["account_id"] = account["account_id"]
        item["account_label"] = account["label"]
        for field in ("resource_id", "name"):
            if isinstance(item.get(field), str):
                item[field] = item[field].replace(MOTO_ACCOUNT_ID, account["account_id"])
        pin_age(item)
        resources.append(item)
    return resources


def summarize(resources: list[dict]) -> dict:
    by_risk: dict[str, int] = {}
    total = 0.0
    for r in resources:
        by_risk[r["risk_level"]] = by_risk.get(r["risk_level"], 0) + 1
        if r.get("estimated_monthly_cost"):
            total += r["estimated_monthly_cost"]
    return {
        "total_resources": len(resources),
        "by_risk_level": by_risk,
        "estimated_monthly_cost": round(total, 2),
    }


def derive_previous(current: list[dict]) -> list[dict]:
    """Build the earlier scan from the current one so IDs stay stable.

    Produces a diff with something in every bucket: two resources appear in the
    current scan, one disappeared, and one changed risk.
    """
    previous = []
    for r in deepcopy(current):
        # These two are the "new since last scan" findings.
        if r["resource_type"] == "NAT Gateway":
            continue
        if r["resource_type"] == "Elastic IP" and r["status"] == "unassociated":
            continue
        # This instance was stopped last week and has since been started —
        # a risk increase the alert engine should notice.
        if r["resource_type"] == "EC2 Instance" and r["name"] == "tutorial-web-server":
            r["status"] = "stopped"
            r["risk_level"] = "LOW"
        previous.append(r)

    # A finding that was cleaned up between scans.
    retired = deepcopy(previous[0])
    retired.update(
        {
            "resource_type": "EBS Volume",
            "resource_id": "vol-0e11a2b3c4d5e6f70",
            "name": "retired-lab-volume",
            "status": "available",
            "risk_level": "MEDIUM",
            "monthly_cost_risk": (
                "Unattached volumes still cost money per GB-month even though "
                "nothing is using them."
            ),
            "suggested_action": (
                "Review this orphaned volume. If it holds no data you need, "
                "snapshot it (optional) and delete it manually."
            ),
            "created_at": _iso(CURRENT_DT - timedelta(days=180)),
            "details": {"size_gb": 50, "volume_type": "gp2"},
            "estimated_monthly_cost": 5.0,
            "cost_source": "static",
        }
    )
    previous.append(retired)
    return previous


def write(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"  wrote {path.relative_to(REPO_ROOT)}")


def main() -> None:
    OUT_DIR.mkdir(exist_ok=True)
    print("Generating demo fixtures from real scanners (moto sandbox)…")

    current = scan_account(seed_sandbox, SANDBOX) + scan_account(seed_training, TRAINING)
    # Highest risk first, so the demo opens on the findings that matter.
    order = {"HIGH": 0, "REVIEW": 1, "MEDIUM": 2, "LOW": 3}
    current.sort(key=lambda r: (order.get(r["risk_level"], 9), r["resource_type"]))
    previous = derive_previous(current)

    write(
        OUT_DIR / "current-scan.json",
        {
            "scan_id": CURRENT_SCAN_ID,
            "created_at": CURRENT_AT,
            "summary": summarize(current),
            "resources": current,
        },
    )
    write(
        OUT_DIR / "previous-scan.json",
        {
            "scan_id": PREVIOUS_SCAN_ID,
            "created_at": PREVIOUS_AT,
            "summary": summarize(previous),
            "resources": previous,
        },
    )
    write(
        OUT_DIR / "alerts.json",
        {"alerts": [a.model_dump(mode="json") for a in evaluate_alerts(current, previous)]},
    )

    # The diff the REAL backend produces for these two scans. The frontend's
    # demo provider computes its own diff locally, so this file is the contract
    # it is tested against — a cross-language check that both sides of the
    # provider boundary emit the same shape. See frontend provider-contract test.
    meta = lambda scan_id, at, resources: {  # noqa: E731
        "scan_id": scan_id,
        "created_at": at,
        "summary": summarize(resources),
    }
    write(
        OUT_DIR / "expected-diff.json",
        {
            "from": meta(PREVIOUS_SCAN_ID, PREVIOUS_AT, previous),
            "to": meta(CURRENT_SCAN_ID, CURRENT_AT, current),
            **diff_resource_lists(previous, current),
        },
    )
    write(
        OUT_DIR / "accounts.json",
        {
            "accounts": [
                {
                    "account_id": SANDBOX["account_id"],
                    "name": SANDBOX["label"],
                    "role_arn": f"arn:aws:iam::{SANDBOX['account_id']}:role/ShutItDownScannerRole",
                    "has_external_id": True,
                    "regions": None,
                    "created_at": "2026-07-02T09:14:22.000Z",
                },
                {
                    "account_id": TRAINING["account_id"],
                    "name": TRAINING["label"],
                    "role_arn": f"arn:aws:iam::{TRAINING['account_id']}:role/ShutItDownScannerRole",
                    "has_external_id": True,
                    "regions": None,
                    "created_at": "2026-07-09T16:41:05.000Z",
                },
            ]
        },
    )

    summary = summarize(current)
    print(
        f"\n{summary['total_resources']} resources · "
        f"${summary['estimated_monthly_cost']}/mo · {summary['by_risk_level']}"
    )


if __name__ == "__main__":
    main()
